;
; File generated by cc65 v 2.14 - Git 1e4a745
;
	.fopt		compiler,"cc65 v 2.14 - Git 1e4a745"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_spr_get
	.export		_spr
	.export		_sync
	.export		_main

.segment	"DATA"

_spr:
	.word	$0000

; ---------------------------------------------------------------
; void __near__ sync (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sync: near

.segment	"CODE"

	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$00
	jsr     _spr_get
	sta     _spr
	stx     _spr+1
	sta     ptr1
	stx     ptr1+1
	lda     #$80
	ldy     #$03
	sta     (ptr1),y
	lda     _spr
	sta     ptr1
	lda     _spr+1
	sta     ptr1+1
	lda     #$80
	ldy     #$00
	sta     (ptr1),y
	lda     _spr
	sta     ptr1
	lda     _spr+1
	sta     ptr1+1
	lda     #$76
	iny
	sta     (ptr1),y
	lda     _spr
	sta     ptr1
	lda     _spr+1
	sta     ptr1+1
	lda     #$00
	iny
	sta     (ptr1),y
L0013:	jmp     L0013

.endproc

